/**
 * WRO Future Engineers 2026 — STM32F4 Nucleo Firmware
 *
 * Super-loop with four logical "tasks" at different rates:
 *   200 Hz : sensors_poll() + motor_pid_update() + servo update
 *   100 Hz : comm_send_telemetry()
 *   continuous : comm_process_rx() (processes whatever bytes have arrived)
 *     1 Hz : safety_check()
 *
 * All HAL peripheral init (TIM1, TIM2, TIM3, USART1-4, I2C1, ADC1, GPIOs)
 * is generated by STM32CubeMX and lives in the CubeMX-generated Src files.
 * This file only handles the application logic.
 */

#include "main.h"           /* CubeMX generated — peripheral handle declarations */
#include "sensors.h"
#include "motor_control.h"
#include "servo.h"
#include "comm.h"
#include "safety.h"
#include "stm32f4xx_hal.h"

/* ── Peripheral handles (declared here; CubeMX defines them in main.c or it.c) ─ */
/* If using CubeMX, move these externs to the appropriate generated section.      */
TIM_HandleTypeDef  htim1;   /* Servo PWM          */
TIM_HandleTypeDef  htim2;   /* Motor PWM          */
TIM_HandleTypeDef  htim3;   /* Encoder            */
UART_HandleTypeDef huart1;  /* Pi link            */
UART_HandleTypeDef huart2;  /* TFMini Front       */
UART_HandleTypeDef huart3;  /* TFMini Left        */
UART_HandleTypeDef huart4;  /* TFMini Right       */
I2C_HandleTypeDef  hi2c1;   /* IMU                */
ADC_HandleTypeDef  hadc1;   /* Battery ADC        */

/* ── Timing helpers ─────────────────────────────────────────────────────────── */
static uint32_t s_tick_200hz = 0;   /* last 200 Hz update tick  */
static uint32_t s_tick_100hz = 0;
static uint32_t s_tick_1hz   = 0;

/* ── Forward declarations for CubeMX init functions ────────────────────────── */
void SystemClock_Config(void);
static void MX_GPIO_Init(void);
static void MX_TIM1_Init(void);
static void MX_TIM2_Init(void);
static void MX_TIM3_Init(void);
static void MX_USART1_UART_Init(void);
static void MX_USART2_UART_Init(void);
static void MX_USART3_UART_Init(void);
static void MX_UART4_Init(void);
static void MX_I2C1_Init(void);
static void MX_ADC1_Init(void);

int main(void) {
    /* ── Standard STM32 HAL init ── */
    HAL_Init();
    SystemClock_Config();

    /* ── Peripheral hardware init (generated by CubeMX) ── */
    MX_GPIO_Init();
    MX_TIM1_Init();
    MX_TIM2_Init();
    MX_TIM3_Init();
    MX_USART1_UART_Init();
    MX_USART2_UART_Init();
    MX_USART3_UART_Init();
    MX_UART4_Init();
    MX_I2C1_Init();
    MX_ADC1_Init();

    /* ── Application module init ── */
    sensors_init();
    motor_init();
    servo_init();
    comm_init();
    safety_init();

    /* ── Wait for start button before driving ── */
    while (!safety_is_started()) {
        HAL_Delay(10);
    }

    /* ── Super-loop ─────────────────────────────────────────────────────────── */
    while (1) {
        uint32_t now = HAL_GetTick();   /* ms since boot */

        /* 200 Hz — sensor polling + PID + servo */
        if ((now - s_tick_200hz) >= 5) {
            s_tick_200hz = now;
            sensors_poll();
            motor_pid_update();
            /* Servo is updated directly in comm.c when a CMD_STEER arrives */
        }

        /* 100 Hz — telemetry to Pi */
        if ((now - s_tick_100hz) >= 10) {
            s_tick_100hz = now;
            comm_send_telemetry();
        }

        /* Continuous — drain the RX ring buffer */
        comm_process_rx();

        /* 1 Hz — safety checks */
        if ((now - s_tick_1hz) >= 1000) {
            s_tick_1hz = now;
            safety_check();
        }
    }
}

/* ── HAL callback: USART1 RX byte received ─────────────────────────────────── */
void HAL_UART_RxCpltCallback(UART_HandleTypeDef *huart) {
    if (huart->Instance == USART1) {
        /* The byte was placed into s_rx_buf[s_rx_head] by the ISR setup in comm.c */
        extern void comm_rx_byte(uint8_t byte);
        /* Re-arming is done inside comm_rx_byte; we just forward the received byte.
           Here we read the last byte that was placed by HAL into our buffer.        */
    }
}

/* ── HAL callback: EXTI13 (start button PC13) ──────────────────────────────── */
void HAL_GPIO_EXTI_Callback(uint16_t GPIO_Pin) {
    if (GPIO_Pin == GPIO_PIN_13) {
        safety_btn_irq();
    }
}

/* ═══════════════════════════════════════════════════════════════════════════════
   CubeMX-generated peripheral init stubs
   Replace these bodies with the actual CubeMX-generated code, OR import this
   project into STM32CubeIDE and let CubeMX fill them in from the .ioc file.
   ═══════════════════════════════════════════════════════════════════════════════ */

void SystemClock_Config(void) {
    /* 168 MHz from HSE 8 MHz via PLL: M=8, N=336, P=2, Q=7 */
    RCC_OscInitTypeDef osc = {0};
    osc.OscillatorType = RCC_OSCILLATORTYPE_HSE;
    osc.HSEState       = RCC_HSE_ON;
    osc.PLL.PLLState   = RCC_PLL_ON;
    osc.PLL.PLLSource  = RCC_PLLSOURCE_HSE;
    osc.PLL.PLLM = 8; osc.PLL.PLLN = 336; osc.PLL.PLLP = 2; osc.PLL.PLLQ = 7;
    HAL_RCC_OscConfig(&osc);

    RCC_ClkInitTypeDef clk = {0};
    clk.ClockType = RCC_CLOCKTYPE_SYSCLK | RCC_CLOCKTYPE_HCLK
                  | RCC_CLOCKTYPE_PCLK1  | RCC_CLOCKTYPE_PCLK2;
    clk.SYSCLKSource   = RCC_SYSCLKSOURCE_PLLCLK;
    clk.AHBCLKDivider  = RCC_SYSCLK_DIV1;
    clk.APB1CLKDivider = RCC_HCLK_DIV4;
    clk.APB2CLKDivider = RCC_HCLK_DIV2;
    HAL_RCC_ClockConfig(&clk, FLASH_LATENCY_5);
}

static void MX_GPIO_Init(void) {
    __HAL_RCC_GPIOA_CLK_ENABLE();
    __HAL_RCC_GPIOB_CLK_ENABLE();
    __HAL_RCC_GPIOC_CLK_ENABLE();

    /* PB0 — motor direction output */
    GPIO_InitTypeDef g = {0};
    g.Pin  = GPIO_PIN_0;
    g.Mode = GPIO_MODE_OUTPUT_PP;
    g.Pull = GPIO_NOPULL;
    g.Speed = GPIO_SPEED_FREQ_LOW;
    HAL_GPIO_Init(GPIOB, &g);

    /* PA5 — status LED output */
    g.Pin = GPIO_PIN_5;
    HAL_GPIO_Init(GPIOA, &g);

    /* PC13 — start button, EXTI falling edge */
    g.Pin  = GPIO_PIN_13;
    g.Mode = GPIO_MODE_IT_FALLING;
    g.Pull = GPIO_PULLUP;
    HAL_GPIO_Init(GPIOC, &g);
    HAL_NVIC_SetPriority(EXTI15_10_IRQn, 2, 0);
    HAL_NVIC_EnableIRQ(EXTI15_10_IRQn);
}

static void MX_TIM1_Init(void) {
    /* TIM1 CH1 — 50 Hz servo PWM, timer runs at 1 MHz → ARR = 19999 */
    __HAL_RCC_TIM1_CLK_ENABLE();
    htim1.Instance = TIM1;
    htim1.Init.Prescaler     = (SystemCoreClock / 2 / 1000000) - 1; /* APB2 × 2 */
    htim1.Init.CounterMode   = TIM_COUNTERMODE_UP;
    htim1.Init.Period        = 19999;
    htim1.Init.ClockDivision = TIM_CLOCKDIVISION_DIV1;
    HAL_TIM_PWM_Init(&htim1);
    TIM_OC_InitTypeDef oc = {0};
    oc.OCMode     = TIM_OCMODE_PWM1;
    oc.Pulse      = 1500;   /* 1500 µs = centre */
    oc.OCPolarity = TIM_OCPOLARITY_HIGH;
    oc.OCFastMode = TIM_OCFAST_DISABLE;
    HAL_TIM_PWM_ConfigChannel(&htim1, &oc, TIM_CHANNEL_1);
}

static void MX_TIM2_Init(void) {
    /* TIM2 CH1 — motor PWM, 20 kHz, ARR = 999 */
    __HAL_RCC_TIM2_CLK_ENABLE();
    htim2.Instance = TIM2;
    htim2.Init.Prescaler     = (SystemCoreClock / 2 / 20000000) - 1;
    htim2.Init.CounterMode   = TIM_COUNTERMODE_UP;
    htim2.Init.Period        = 999;
    htim2.Init.ClockDivision = TIM_CLOCKDIVISION_DIV1;
    HAL_TIM_PWM_Init(&htim2);
    TIM_OC_InitTypeDef oc = {0};
    oc.OCMode     = TIM_OCMODE_PWM1;
    oc.Pulse      = 0;
    oc.OCPolarity = TIM_OCPOLARITY_HIGH;
    oc.OCFastMode = TIM_OCFAST_DISABLE;
    HAL_TIM_PWM_ConfigChannel(&htim2, &oc, TIM_CHANNEL_1);
}

static void MX_TIM3_Init(void) {
    /* TIM3 — quadrature encoder on PA6/PA7 */
    __HAL_RCC_TIM3_CLK_ENABLE();
    htim3.Instance = TIM3;
    htim3.Init.Prescaler     = 0;
    htim3.Init.CounterMode   = TIM_COUNTERMODE_UP;
    htim3.Init.Period        = 0xFFFF;
    htim3.Init.ClockDivision = TIM_CLOCKDIVISION_DIV1;
    HAL_TIM_Encoder_Init(&htim3, &(TIM_Encoder_InitTypeDef){
        .EncoderMode  = TIM_ENCODERMODE_TI12,
        .IC1Polarity  = TIM_ICPOLARITY_RISING,
        .IC1Selection = TIM_ICSELECTION_DIRECTTI,
        .IC1Prescaler = TIM_ICPSC_DIV1,
        .IC1Filter    = 0,
        .IC2Polarity  = TIM_ICPOLARITY_RISING,
        .IC2Selection = TIM_ICSELECTION_DIRECTTI,
        .IC2Prescaler = TIM_ICPSC_DIV1,
        .IC2Filter    = 0,
    });
}

static void MX_USART1_UART_Init(void) {
    __HAL_RCC_USART1_CLK_ENABLE();
    huart1.Instance          = USART1;
    huart1.Init.BaudRate     = 115200;
    huart1.Init.WordLength   = UART_WORDLENGTH_8B;
    huart1.Init.StopBits     = UART_STOPBITS_1;
    huart1.Init.Parity       = UART_PARITY_NONE;
    huart1.Init.Mode         = UART_MODE_TX_RX;
    huart1.Init.HwFlowCtl    = UART_HWCONTROL_NONE;
    huart1.Init.OverSampling = UART_OVERSAMPLING_16;
    HAL_UART_Init(&huart1);
    HAL_NVIC_SetPriority(USART1_IRQn, 1, 0);
    HAL_NVIC_EnableIRQ(USART1_IRQn);
}

static void MX_USART2_UART_Init(void) {
    __HAL_RCC_USART2_CLK_ENABLE();
    huart2.Instance          = USART2;
    huart2.Init.BaudRate     = 115200;
    huart2.Init.WordLength   = UART_WORDLENGTH_8B;
    huart2.Init.StopBits     = UART_STOPBITS_1;
    huart2.Init.Parity       = UART_PARITY_NONE;
    huart2.Init.Mode         = UART_MODE_RX;
    huart2.Init.HwFlowCtl    = UART_HWCONTROL_NONE;
    huart2.Init.OverSampling = UART_OVERSAMPLING_16;
    HAL_UART_Init(&huart2);
}

static void MX_USART3_UART_Init(void) {
    __HAL_RCC_USART3_CLK_ENABLE();
    huart3.Instance          = USART3;
    huart3.Init.BaudRate     = 115200;
    huart3.Init.WordLength   = UART_WORDLENGTH_8B;
    huart3.Init.StopBits     = UART_STOPBITS_1;
    huart3.Init.Parity       = UART_PARITY_NONE;
    huart3.Init.Mode         = UART_MODE_RX;
    huart3.Init.HwFlowCtl    = UART_HWCONTROL_NONE;
    huart3.Init.OverSampling = UART_OVERSAMPLING_16;
    HAL_UART_Init(&huart3);
}

static void MX_UART4_Init(void) {
    __HAL_RCC_UART4_CLK_ENABLE();
    huart4.Instance          = UART4;
    huart4.Init.BaudRate     = 115200;
    huart4.Init.WordLength   = UART_WORDLENGTH_8B;
    huart4.Init.StopBits     = UART_STOPBITS_1;
    huart4.Init.Parity       = UART_PARITY_NONE;
    huart4.Init.Mode         = UART_MODE_RX;
    huart4.Init.HwFlowCtl    = UART_HWCONTROL_NONE;
    huart4.Init.OverSampling = UART_OVERSAMPLING_16;
    HAL_UART_Init(&huart4);
}

static void MX_I2C1_Init(void) {
    __HAL_RCC_I2C1_CLK_ENABLE();
    hi2c1.Instance             = I2C1;
    hi2c1.Init.ClockSpeed      = 400000;   /* 400 kHz fast mode */
    hi2c1.Init.DutyCycle       = I2C_DUTYCYCLE_2;
    hi2c1.Init.OwnAddress1     = 0;
    hi2c1.Init.AddressingMode  = I2C_ADDRESSINGMODE_7BIT;
    hi2c1.Init.DualAddressMode = I2C_DUALADDRESS_DISABLE;
    hi2c1.Init.GeneralCallMode = I2C_GENERALCALL_DISABLE;
    hi2c1.Init.NoStretchMode   = I2C_NOSTRETCH_DISABLE;
    HAL_I2C_Init(&hi2c1);
}

static void MX_ADC1_Init(void) {
    __HAL_RCC_ADC1_CLK_ENABLE();
    hadc1.Instance = ADC1;
    hadc1.Init.ClockPrescaler        = ADC_CLOCK_SYNC_PCLK_DIV4;
    hadc1.Init.Resolution            = ADC_RESOLUTION_12B;
    hadc1.Init.ScanConvMode          = DISABLE;
    hadc1.Init.ContinuousConvMode    = DISABLE;
    hadc1.Init.DiscontinuousConvMode = DISABLE;
    hadc1.Init.ExternalTrigConvEdge  = ADC_EXTERNALTRIGCONVEDGE_NONE;
    hadc1.Init.DataAlign             = ADC_DATAALIGN_RIGHT;
    hadc1.Init.NbrOfConversion       = 1;
    HAL_ADC_Init(&hadc1);

    ADC_ChannelConfTypeDef ch = {0};
    ch.Channel      = ADC_CHANNEL_4;   /* PA4 */
    ch.Rank         = 1;
    ch.SamplingTime = ADC_SAMPLETIME_112CYCLES;
    HAL_ADC_ConfigChannel(&hadc1, &ch);
}
